(#1) Criacao do projeto inicial
demarte/open-weather pull request #4
Opened 2019-02-10 01:41 UTC by demarte

Fixes: #1

### Descrição:
Criaçāo do projeto inicial (Single View App) utilizando Xcode 10.1. 

### Testes:
* [ ]  O projeto funciona após minhas mudanças

### Screenshoots:

2019-02-10 21:34 UTC, brunoreginato requested changes
Ótimo começo! 

Deixei algumas sugestões sobre codigo auto-gerado, considere resolve-las.
Além disso, acho que você se esqueceu do conteudo do arquivo `.gitignore`.

Esse site da bons exemplos de `.gitignore`:

https://www.gitignore.io/api/swift

2019-02-10 21:34 UTC, brunoreginato commented on OpenWeatherApp/AppDelegate.swift
> +    func applicationWillResignActive(_ application: UIApplication) {
Você pode remover os metodos da linha 22 a 42 dado que eles são boilerplates.

2019-02-10 21:34 UTC, brunoreginato commented on OpenWeatherApp/AppDelegate.swift
> +        // Override point for customization after application launch.
Eu removeria esse comentário.

2019-02-10 21:34 UTC, brunoreginato commented on OpenWeatherApp/AppDelegate.swift
> +
linha extra, pode remove-la por favor?

2019-02-10 21:34 UTC, brunoreginato commented on OpenWeatherApp/ViewController.swift
> +//
Eu entendo que é um arquivo auto gerado porém eu não gosto de ter algo que não está sendo usado no projeto.
Minha sugestão é remover o mesmo (não se esqueça das referências no storyboard.)

2019-02-10 21:40 UTC, brunoreginato commented
Outro ponto é que haviamos falado sobre os pull request templates, lembra?

Segue um tutorial de como cria-los:
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

Pode adiciona-lo a esse PR também.

2019-02-10 23:20 UTC, demarte commented
Beleza Bruno. Vou corrigir esses tópicos. O git ignore eu nāo sabia como faze-lo e só criei o arquivo. Vou cria-lo da maneira correta e fazer a refatoraçāo.

2019-02-11 01:48 UTC, demarte commented
Tenho uma duvida. No .gitignore eu devo colocar o arquivo gerado por aquela api, ou eu vou adicionando o que eu quero ignorar aos poucos? Porque no segundo caso, acho que por enquanto nao tenho nada para ignorar.

2019-02-11 23:28 UTC, brunoreginato commented
> Tenho uma duvida. No .gitignore eu devo colocar o arquivo gerado por aquela api, ou eu vou adicionando o que eu quero ignorar aos poucos? Porque no segundo caso, acho que por enquanto nao tenho nada para ignorar.

Fica a teu gosto. Eu normalmente já coloco tudos dado que o projeto irá evoluir. Sobre ter algo a ignorar, na verdade, temos sim. Existem alguns arquivos que o o Xcode gera que são individuas de cada desenvolvedor (`xcuserdata`)

2019-02-11 23:32 UTC, brunoreginato commented
https://github.com/demarte/open-weather/pull/4/commits/75a3bef193b914c698eb4e616f66a9957bcc06d5

Sobre code-style guide, se quiser ter algo automatizado para fazer esse trabalho, sugiro o [SwiftLint](https://github.com/realm/SwiftLint)

Ele tem um modo que não utiliza o Cocoapods e a cada build valida o code-style do teu código.

2019-02-11 23:50 UTC, demarte commented
Bom eu vou adicionar aquele arquivo gerado ao .gitignore, e vou analisando os arquivos do projeto daquela lista aos poucos. Sobre o code-style, acho que vou continuar olhando na documentação do [raywenderlich](https://github.com/raywenderlich/swift-style-guide) pra esse projeto, acho que assim eu consigo pesquisar mais. Mas curti esse SwiftLint, é bem massa.

2019-02-12 10:39 UTC, brunoreginato commented
Apenas mais um detalhe, me parece que o arquivo `ViewController.swift` não foi removido, pode checar isso antes de fazermos o merge?

2019-02-12 11:38 UTC, demarte commented
Ah... eu removi ele do repositório local e quando fiz o push o arquivo manteve no repositório remoto. É normal isso?

2019-02-12 11:39 UTC, demarte commented
Se eu der o comando -force acho que resolve, porem essa é a melhor pratica nesse caso?

2019-02-12 11:43 UTC, demarte commented
Tenho outra duvida. E so irei abrir a branch (#2) a partir da development depois que nos fizermos o merge desse PR? Porque eu comecei a trabalhar na branch (#2) porem em um outro projeto teste.

2019-02-12 12:57 UTC, brunoreginato commented
> Se eu der o comando -force acho que resolve, porem essa é a melhor pratica nesse caso?

O force só deve ser utilizado em momentos de "merdaço" total então esqueça que ele existe.

Você provavelmente só removeu a referencia do arquivo no projeto, da uma olhada na pasta física ele deve estar lá.

> Tenho outra duvida. E so irei abrir a branch (#2) a partir da development depois que nos fizermos o merge desse PR? Porque eu comecei a trabalhar na branch (#2) porem em um outro projeto teste.

Exatamente, você só deve abrir a #2 depois de finalizar a #1 pelo fato delas serem dependentes. Existem algumas situações que daria pra você trabalhar em paralelo.

2019-02-12 13:52 UTC, demarte commented
> O force só deve ser utilizado em momentos de "merdaço" total então esqueça que ele existe.
> 
> Você provavelmente só removeu a referencia do arquivo no projeto, da uma olhada na pasta física ele deve estar lá.

Exatamente, eu dei delete na māo e escolhi a opção de remover a referencia

2019-02-12 13:54 UTC, brunoreginato approved these changes
Muito bom! Podemos fazer o merge!

2019-02-12 14:09 UTC, merged